### PR TITLE
Add serial over USB with external phy using interrupts example

### PR DESCRIPTION
**Pull request by olback**

### CODE REVIEW

**Comment by richardeoin** [comment]
Thanks, very nice!

**Comment by richardeoin** [comment]
It fails to build the example for STM32H735 because the interrupts are missing, fixed here https://github.com/stm32-rs/stm32-rs/pull/677

Solution for now is just to build the example for a single family

**Comment by richardeoin** [comment]
@olback Which PHY did you test this with?

**Comment by olback** [comment]
I tested on an Arduino H7. It uses a [Microchip USB3320C](https://www.microchip.com/en-us/product/USB3320).

**Comment by richardeoin** [comment]
Ok, great! Same as the H747I-DISCO development board I have

**Pull request merged**
