### PR TITLE
Add an example of QSPI used for flash memory

### PR DESCRIPTION
**Pull request by phoracek**
This demo uses QSPI interface to interact with the flash memory
available on Daisy Seed board. This simple implementation shows how to
reset registries, read and write values within a single section.

In the demo, a restart counter is stored in flash and its value is
indicated through LED.

Signed-off-by: Petr Horacek <hrck@protonmail.com>

### CODE REVIEW

**Comment by x37v** [comment]
@phoracek i've had success with the 4-bit mode on the daisy, if you're interested.. https://github.com/x37v/libdaisy-rust/blob/xnor/is25lp/src/flash.rs

still a WIP though.

**Comment by richardeoin** [comment]
Thanks for the PR! It would be helpful to have a QSPI Flash example for the HAL, and this one seems very nice!

It would be even better if it's possible to use 4-bit mode without too many extra complications. Otherwise I'm also happy to use it as-is.

**Comment by phoracek** [comment]
@x37v that is awesome, thanks a lot (and interesting additions in your fork)! With that, I was able to get the example work in the quad mode.

So with this, I think it should be ready for review. The example with "persistent LED state" is not very useful, but I found it fun. I am fine switching it to "create lot of data, save it, read it back" demo too, if that sounds better.

**Comment by richardeoin** [comment]
I merged this example into https://github.com/stm32-rs/stm32h7xx-hal/pull/230. Thanks @phoracek !

**Comment by phoracek** [comment]
Awesome, thank you o/

**Pull request merged**
